"""Central path configuration for the ShopWiser pipeline (cwd-independent)."""

import sys
from pathlib import Path

# src/shopwiser/paths.py -> parents[2] = repository root
PROJECT_ROOT = Path(__file__).resolve().parents[2]


def ensure_repo_on_syspath() -> None:
    """Put the repo root on ``sys.path`` so ``import tests.…`` works under ``python -m``."""
    r = str(PROJECT_ROOT)
    if r not in sys.path:
        sys.path.insert(0, r)

# Four purpose-based data folders:
#   input/        raw scrapes + normalised features (pipeline inputs)
#   intermediate/ matcher + ensemble outputs (regenerated by the pipeline)
#   deliverable/  the final output (ensemble_clusters_final.csv)
#   validation/   acceptance validation, charts, review form
DATA_INPUT = PROJECT_ROOT / "data" / "input"
DATA_INTERMEDIATE = PROJECT_ROOT / "data" / "intermediate"
DATA_DELIVERABLE = PROJECT_ROOT / "data" / "deliverable"
DATA_VALIDATION = PROJECT_ROOT / "data" / "validation"

RAW_CSV = "raw.csv"
RAW_1000_CSV = "raw_1000.csv"
NORMALIZED_PRODUCTS_CSV = "normalized_products.csv"
NORMALIZED_SAMPLE_CSV = "normalized_products_sample.csv"


def raw_csv_path(*, sample: bool = False) -> Path:
    """Full scrape vs ~1000-row development slice in ``data/input/``."""
    return DATA_INPUT / (RAW_1000_CSV if sample else RAW_CSV)


def normalized_products_path(*, sample: bool = False) -> Path:
    """Normalised features written by the normalisation step (full vs sample run)."""
    name = NORMALIZED_SAMPLE_CSV if sample else NORMALIZED_PRODUCTS_CSV
    return DATA_INPUT / name


def cluster_outputs_path(*, sample: bool = False) -> Path:
    """Matcher/ensemble outputs. Sample runs use an ``intermediate/sample`` subfolder
    so they do not overwrite the full-run artefacts."""
    return (DATA_INTERMEDIATE / "sample") if sample else DATA_INTERMEDIATE


def ml_matching_outputs_path(*, sample: bool = False) -> Path:
    """ML matcher writes alongside the other intermediate artefacts."""
    return (DATA_INTERMEDIATE / "sample") if sample else DATA_INTERMEDIATE


# Backwards-compatible defaults (full dataset)
INPUT_RAW = raw_csv_path(sample=False)
NORMALIZED_PRODUCTS = normalized_products_path(sample=False)
